compressionLevel: mixed

enableGlobalCache: false

npmScopes:
  here:
    npmRegistryServer: "https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
